In [1]:
import numpy as np


In [2]:
A=np.array([1,2,3])
A

array([1, 2, 3])

In [3]:
A.data

In [4]:
A.shape

(3,)

In [5]:
A.size

3

In [7]:
A.nbytes

12

In [9]:
A.ndim

1

In [10]:
A.dtype

dtype('int32')

In [20]:
V=np.array([1,2,3,4],ndmin=5)
V


array([[[[[1, 2, 3, 4]]]]])

In [19]:
V.ndim

5

In [24]:
arange=np.arange(1,10,2)
arange

array([1, 3, 5, 7, 9])

In [29]:
identity=np.identity(4,dtype='int')
identity

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [49]:
S=np.array([1, 2, 3, 4, 5, 6, 7])
print(S[2])

3


In [50]:
print(S[1]+S[3])

6


In [51]:
print(S[1:3])

[2 3]


In [52]:
print(S[1:]) #positive slicing

[2 3 4 5 6 7]


In [53]:
print(S[-1:])#negative slicing

[7]


In [55]:
print(S[1:5:2])

[2 4]


In [58]:
print(S[::3])

[1 4 7]


In [59]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [60]:


arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [61]:


arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [62]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [63]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [66]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')
print(arr)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
[1 2 3]
int32


In [71]:
arr=([1,2,3,7,8])

arr[0]=10
arr


[10, 2, 3, 7, 8]

In [72]:
x=arr.copy()
x

[10, 2, 3, 7, 8]

In [73]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [74]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()




None
[1 2 3 4 5]


In [75]:
print(x.base)

None


In [76]:
print(y.base)

[1 2 3 4 5]


In [77]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [84]:
A=np.array([1,2,3,4,5,6,7,8])
B=(A.reshape(2,4))
print(B)

[[1 2 3 4]
 [5 6 7 8]]


In [86]:
B=(A.reshape(2,4).base)
B

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
C=(B.reshape(-1))
C

array([1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [89]:
type(newarr)

numpy.ndarray