In [1]:
import numpy as np


In [2]:
A=np.array([1,2,3,4,],ndmin=5)
A

array([[[[[1, 2, 3, 4]]]]])

In [3]:
A.ndim

5

In [4]:
A.shape

(1, 1, 1, 1, 4)

In [10]:
A.reshape(2,2,-1)

array([[[1],
        [2]],

       [[3],
        [4]]])

In [11]:
import numpy as np

In [19]:
c=np.array([1,4,3,5,6,9])
b=np.array([3,2,4,6,2,8])


[1 4 3 5 6 9]


In [21]:
c.shape

(6,)

In [29]:
s=c.reshape(2,3)
s.ndim

2

In [27]:
c.reshape(2,3,-1)



array([[[1],
        [4],
        [3]],

       [[5],
        [6],
        [9]]])

In [33]:
d=np.identity(4,dtype='int')
d


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [34]:
s=np.full([3,3],9)
s

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [37]:
x=np.ones([2,3],dtype='int')
x

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
#numpy join 
#concatenate
D=np.concatenate((c,b))
D

array([1, 4, 3, 5, 6, 9, 3, 2, 4, 6, 2, 8])

In [42]:
h=np.array([3,3,46,1,5,6,78])
h

array([ 3,  3, 46,  1,  5,  6, 78])

In [43]:
Q=np.concatenate((D,h))
Q

array([ 1,  4,  3,  5,  6,  9,  3,  2,  4,  6,  2,  8,  3,  3, 46,  1,  5,
        6, 78])

In [44]:
Q.size

19

In [45]:
Q.nbytes

76

In [46]:
np.repeat(2,3)

array([2, 2, 2])

In [47]:
c=np.array([3,4,5,3,6,2])
F=np.array([6,7,5,7,8,6])

In [51]:
S=np.stack((c,F),axis=1)
S

array([[3, 6],
       [4, 7],
       [5, 5],
       [3, 7],
       [6, 8],
       [2, 6]])

In [53]:
H=np.vstack((c,F))
H

array([[3, 4, 5, 3, 6, 2],
       [6, 7, 5, 7, 8, 6]])

In [54]:
p=np.hstack((c,F))
p

array([3, 4, 5, 3, 6, 2, 6, 7, 5, 7, 8, 6])

In [57]:
j=np.concatenate((c,F))
j

array([3, 4, 5, 3, 6, 2, 6, 7, 5, 7, 8, 6])

In [62]:
split=np.array_split(j,3)
split

[array([3, 4, 5, 3]), array([6, 2, 6, 7]), array([5, 7, 8, 6])]

In [63]:
print(split[0])

[3 4 5 3]


In [64]:
print(split[2])

[5 7 8 6]


In [69]:
d_2=np.array([[2,3,2,2,3,1,5,6,6],[2,3,2,2,3,1,5,4,2]])


In [70]:
d_2.shape

(2, 9)

In [71]:
d_2.ndim

2

In [82]:
Spl_it=np.array_split(d_2,4)


In [83]:
Spl_it

[array([[2, 3, 2, 2, 3, 1, 5, 6, 6]]),
 array([[2, 3, 2, 2, 3, 1, 5, 4, 2]]),
 array([], shape=(0, 9), dtype=int32),
 array([], shape=(0, 9), dtype=int32)]

In [84]:
z=np.concatenate((d_2[0],d_2[1]))
z


array([2, 3, 2, 2, 3, 1, 5, 6, 6, 2, 3, 2, 2, 3, 1, 5, 4, 2])

In [85]:
Z=np.stack((d_2[0],d_2[1]),axis=1)
Z


array([[2, 2],
       [3, 3],
       [2, 2],
       [2, 2],
       [3, 3],
       [1, 1],
       [5, 5],
       [6, 4],
       [6, 2]])

In [86]:
#Array search

In [87]:
import numpy as np

In [95]:
Arr=np.array([11,2,33,4,55,4,4,6])
F=np.where(Arr==4)
F
#shows the index

(array([3, 5, 6], dtype=int64),)

In [98]:
#find the odd number
C=np.where(Arr%2!=0)
C

(array([0, 2, 4], dtype=int64),)

In [99]:

x = np.searchsorted(Arr,33)
x

2

In [100]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [101]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [102]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [103]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [107]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])

50


In [109]:
#filter array
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [110]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
