In [12]:
# array atrributes
import numpy as np



In [20]:
a=np.array([1,2,3,5,6,3])
print(a)
a.shape #check how many number
a.ndim #check dimension

[1 2 3 5 6 3]


1

In [15]:
type(a)

list

In [26]:
#two dimentional array
b=np.array([[1,2,3,7],
           [4,5,6,7]])

In [27]:
b.shape

(2, 4)

In [28]:
type(b)

numpy.ndarray

In [29]:
b.ndim

2

In [53]:
#three dimentional array
c=np.array([[
    [1.0,2,3,4],
    [5,6,7,8],
    [33,23,12,45]
],[
    [1,2,3,4],
    [1,2,3,4],
    [5,6,7,8]
]])


In [52]:
type(c)

numpy.ndarray

In [56]:
c.ndim

3

In [55]:
c.shape

(2, 3, 4)

In [54]:
c.dtype

dtype('float64')

In [57]:
b.size ,c.size #determine how many elements ara ther in an array


(8, 24)

In [59]:
b.nbytes,c.nbytes  #bytes consume by this array

(32, 192)

In [66]:
b.data,c.data

(<memory at 0x0000027A95A9D150>, <memory at 0x0000027A95ADC400>)

In [67]:
#array creation



In [68]:
array1=np.array([3,4,2],dtype='int')

In [69]:
array1

array([3, 4, 2])

In [71]:
max(array1)

4

In [73]:
D=np.zeros((3,4),dtype='float')

In [74]:
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
D.shape

(3, 4)

In [80]:
B=np.zeros((3,4),dtype='int')
B


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [82]:
B.shape


(3, 4)

In [84]:
B.nbytes

48

In [85]:
B.data

In [86]:
B.size

12

In [87]:
One=np.ones((3,3),dtype='int')
One

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [88]:
One.size

9

In [89]:
One.shape

(3, 3)

In [90]:
One.nbytes

36

In [93]:
Full=np.full((7,8),9)
Full

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

In [94]:
Full.dtype

dtype('int32')

In [95]:
Full.shape

(7, 8)

In [98]:
identity=np.identity(4,dtype='int')

In [99]:
identity

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [103]:
eye =np.eye(3,3,-1)
eye

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [104]:
arange=np.arange(1,10,2)
arange

array([1, 3, 5, 7, 9])

In [107]:
linspace=np.linspace(1,5,10)
linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [109]:
linspace.size

10

In [113]:
linspace=np.linspace(1,5,30,dtype='int')
linspace

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       4, 4, 4, 4, 4, 4, 4, 5])

In [115]:
empty=np.empty((1,5))
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061821e-306, 3.44886448e-307]])

In [117]:
for i in range(5):
    empty[:,i]=i
empty

array([[0., 1., 2., 3., 4.]])